project_id = "ibhvjdnucfmdfmlmnlif"

[functions.award-leaderboard-cards]
verify_jwt = false

[functions.update-challenge-stats]
verify_jwt = false

[functions.generate-examples]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.award-season-rewards]
verify_jwt = false
